name: running bandit on python code
run-name: bandit_analysis

on:
  workflow_run:
    workflows: ["pytest"]
    types:
      - completed

env:
  PYTHON_VERSION: 3.11

jobs:
  checkout:
    runs-on: ubuntu-latest
    steps:

      - name: Checkout
        uses: actions/checkout@v3

  setup_python:
    runs-on: ubuntu-latest
    needs: checkout
    steps:

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

  run_bandit:
    runs-on: ubuntu-latest
    needs: setup_python
    steps:

      - name: Install Bandit
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: Run Bandit
        run: |
          bandit -r ./app -f json -o bandit_report.json --exit-zero

  report_bandit:
    runs-on: ubuntu-latest
    needs: run_bandit
    steps:
      - name: Convert Bandit Report to Markdown
        run: python githubaction_scripts/convert_bandit_report_to_markdown.py

      - name: Parse Bandit Report for High Severity Issues
        run: python githubaction_scripts/parse_bandit_output.py
        if: always()

      - name: Upload Bandit Report
        uses: actions/upload-artifact@v4
        with:
          name: bandit-report
          path: bandit_report.md
        if: always()

      - name: Add Bandit Report to Job Summary
        run: cat bandit_report.md >> $GITHUB_STEP_SUMMARY
        if: always()