name: running bandit on python code
run-name: bandit_analysis

on:
  push:
    branches:
      - 'main'
      - 'test'

env:
  PYTHON_VERSION: 3.11

jobs:
  bandit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Bandit
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: Run Bandit
        run: |
          bandit -r ./app -f json -o bandit_report.json --exit-zero

      - name: Upload Bandit Report
        uses: actions/upload-artifact@v3
        with:
          name: bandit-report
          path: bandit_report.json

      - name: Display Bandit Report
        id: bandit
        run: cat bandit_report.json

      - name: Create Bandit Report Comment
        uses: actions/github-script@v6
        with:
          script: |
            const fs = require('fs');
            const report = JSON.parse(fs.readFileSync('bandit_report.json', 'utf8'));

            let summary = "## Bandit Security Analysis Report\n";
            summary += "| Issue Severity | Issue Confidence | File | Line | Issue Text |\n";
            summary += "| --- | --- | --- | --- | --- |\n";
            report.results.forEach(issue => {
              summary += `| ${issue.issue_severity} | ${issue.issue_confidence} | ${issue.filename} | ${issue.line_number} | ${issue.issue_text} |\n`;
            });

            if (report.results.length > 0) {
              summary += "\n### Issues Summary\n";
              summary += `**Total Issues Found:** ${report.results.length}\n`;
            } else {
              summary += "\n**No issues found.**\n";
            }

            const { GITHUB_SHA } = process.env;
            await github.rest.issues.createComment({
              ...context.repo,
              issue_number: context.issue.number,
              body: summary,
            });

