name: running bandit on python code
run-name: bandit_analysis

on:
  push:
    branches:
      - 'main'
      - 'test'

env:
  PYTHON_VERSION: 3.11

jobs:
  bandit:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      packages: write
    steps:

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install Bandit
        run: |
          python -m pip install --upgrade pip
          pip install bandit

      - name: Run Bandit
        run: |
          bandit -r ./app -f json -o reports/bandit_report.json --exit-zero

      - name: Upload Bandit Report
        uses: actions/upload-artifact@v3
        with:
          name: bandit-report
          path: reports/bandit_report.json

      - name: Test Report
        uses: dorny/test-reporter@v1
        if: always()
        with:
          name: bandit-fancy-report
          path: reports/bandit_report.json
          reporter: rspec-json ## see https://github.com/marketplace/actions/test-reporter#supported-formats