name: running pip-audit on python code
run-name: pip_audit_analysis

on:
  push:
    branches:
      - 'main'
      - 'test'

jobs:
  pip_audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: install
        run: python -m pip install .

      - name: run pip_audit
        uses: pypa/gh-action-pip-audit@v1.0.8