name: running pip-audit on python code
run-name: pip_audit_analysis

on:
  workflow_run:
    workflows: ["pytest"]
    types:
      - completed

jobs:
  pip_audit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: install
        run: python -m pip install -r requirements.txt

      - name: run pip_audit
        uses: pypa/gh-action-pip-audit@v1.0.8
        with:
          summary: true